### ISSUE TITLE
Error with Logging

### ISSUE THREAD

**Issue by johntrue15** [dbsoft42/adsb-data-collector-mongodb#4]
Hello,

I have tried to setup the Mongodb and the git clone.

However I am receiving error messages about the logging.

I put ' ' around the Logging.info and logging.Critical to get it to run, but then the error "local variable 'logger' referenced before assignment occurs.

Please let me know if you are aware of any fix.

[-John]

![Errors](https://user-images.githubusercontent.com/65981672/120693342-bdc8fb00-c45d-11eb-9af8-038b9be6a007.png)

**Comment by dbsoft42** [comment]
Hi John,

Sorry for not responding earlier. I missed the line to import the logging
package in the config_template.py file and that was causing the problem for
you. I have just pushed a commit with the fix.

You just need to add the "import logging" line (line 5) from the updated
config_template.py file to your config.py file. You don't need the quotes
that you tried adding. Please let me know if this fixes it for you.

Best regards,
Debarka

**Comment by dbsoft42** [comment]
I believe this is resolved now, so closing it.

**Comment by johntrue15** [comment]
Hello,

Thank you for helping me with this 🙂

-John
________________________________
